In [2]:
import numpy as np
import pandas as pd

engineers = pd.read_csv('data/engineers.csv')

engineers

,Name,System,Invite,Unlock,from
0,Bitch-Ass Tod,Wolf397,earn 15 bounty vouchers,100k bounty vouchers,
1,Bill Turner,Alioth,friendly with Alliance,50 units Bromellite,Selene Jean
2,Elvira Martuuk,Khun,travel 300ly,3 units Soontil Relics,
3,The Dweller,Wyrd,deal in 5 black markets,pay 500k cr,
4,Felicity Farseer,Deciat,exploration rank Scout,1 unit Meta-alloys,
5,Liz Ryder,Eyrybia,friendly with Eurybia Blue Mafia,200 units Landmines,
6,Mel Brandon,Luchtaine,invitation from Colonia Council,100k bounty vouchers,Elvira Martuuk
7,Marsha Hicks,Tir,exploration rank Surveyor,Mine 10 Osmium,The Dweller
8,Juri Ishmaak,Giryak,50 combat bonds,provide 100k to 1mil combat bonds,Felicity Farseer
9,Petra Olmanova,Asura,combat rank Expert,200 units Progenitor Cells,Bitch-Ass Tod
10,Etienne Dorn,Los,trade rank Dealer,25 units Occupied Escape Pods,Liz Ryder
11,Zacariah Nemo,Yoru,invitation from Party of Yoru,25 units Xihe Companions,Elvira Martuuk
12,Lei Cheung,Laksak,trade in 50 markets,200 units Gold,The Dweller
13,Bris Dekker,Sol,Friendly with Federation,1-10 million Federal combat bonds,Juri Ishmaak
14,Selene Jean,Kuk,mine 500 ore,10 units Painite,Bitch-Ass Tod
15,Hera Tani,Kuwemaki,Imperial rank Outsider,50 units Kamitra Cigars,Liz Ryder
16,Marco Qwent,Sirius,invitation from Sirius Corp.,25 units Modular Terminals,Elvira Martuuk
17,Ram Tah,Meene,exploration rank Surveyor,50 units Classified Scan Databanks,Lei Cheung
18,The Sarge,Beta-3 Tucani,Federal rank Midshipman,50 units Aberrant Shield Pattern Analysis,Juri Ishmaak
19,Didi Vatermann,Leesti,trade rank Merchant,50 units Lavian Brandy,Selene Jean
20,Broo Tarquin,Muang,combat rank Competent,50 units Fujin Tea,NaN
21,Professor Palin,Arque,travel 5000ly,25 units Sensor Fragments,Marco Qwent
22,Lori Jameson,Shinrarta Dezhra,combat rank Dangerous,25 units Kongga Ale,Marco Qwent
23,Chloe Sedesi,Shenve,travel 5000ly,25 units Sensor Fragments,Marco Qwent
24,Tiana Fortune,Achenar,friendly with Empire,50 units Decoded Emission Data,Hera Tani
25,Domino Green,Orishis,travel 100ly in shuttles,5 doses Push,NaN
26,Kit Fowler,Capoya,sell 10 opinion polls,5 units Surveillance Equipment,Domino Green

In [3]:
mats = pd.read_json('data/footydata.json')

mats

                       name                                 locations
0             Accident Logs           [RES, PWR, IND, HAB, EXT, AGRI]
1       Air Quality Reports  [STO, PWR, IND, HAB, EXT, AGRI, MISSION]
2          Atmospheric Data          [IMARK, RES, IND, CSAT, MISSION]
3                Audio Logs                      [CMD, SETT, MISSION]
4            AX Combat Logs                                     [CMD]
..                      ...                                       ...
108                   Virus                                        []
109        Visitor Register                                     [HAB]
110        Weapon Inventory                            [CMD, MISSION]
111        Weapon Test Data                            [CMD, MISSION]
112  Xeno-Defence Protocols                                        []

[113 rows x 2 columns]